version: '2.1'

services:
  # The NGINX server is just here
  # to serve static assets because Rails is pretty bad for this purpose.
  # TLS stuff can be handled by router like Traefik.
  web:
    image: nginx:1.13-alpine
    container_name: standardfile_web
    ports:
      - "8080:80"
    volumes_from:
      - standardfile:ro
    links:
      - standardfile:app-container
    depends_on:
      - standardfile
    restart: always

  standardfile:
    image: standardfile
    container_name: standardfile_app
    links:
      - database:database
    depends_on:
      - database
    environment:
      # Database connection
      DB_HOST: database
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: standardfile
    restart: always

  database:
    image: mysql
    container_name: standardfile_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
