version: '2'

services:
  # The NGINX server is just here
  # to serve static assets because Rails is pretty bad for this purpose.
  # TLS stuff can be handled by router like Traefik.
  web:
    image: nginx:1.13-alpine
    ports:
      - "8080:80"
    volumes_from:
      - standardnotes:ro
    links:
      - standardnotes:app-container
    restart: always

  standardnotes:
    image: standardnotes
    links:
      - database:database
    environment:
      # Database connection
      DB_HOST: database
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: standardfile
    restart: always

  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
